pipeline:
  build:
    image: docker:18.03.1-ce
    environment:
      - DOCKER_HOST=tcp://docker:2375
      - DOCKER_VERSION=18.03.1-ce
      - COMPOSE_VERSION=1.21.2
      - KUBECTL_VERSION=v1.10.3
    commands:
      - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      - docker build --build-arg=COMPOSE_VERSION=$COMPOSE_VERSION --build-arg=DOCKER_VERSION=$DOCKER_VERSION --build-arg=KUBECTL_VERSION=$KUBECTL_VERSION --no-cache --tag=akalipetis/ci:$DOCKER_VERSION-$COMPOSE_VERSION-$KUBECTL_VERSION .
      - docker push akalipetis/ci:$DOCKER_VERSION-$COMPOSE_VERSION-$KUBECTL_VERSION
    secrets:
      - source: docker-hub-username
        target: docker_username
      - source: docker-hub-password
        target: docker_password

services:
  docker:
    image: docker:18.03.1-ce-dind
    command: [ "--storage-driver=aufs", "--tls=false" ]
    privileged: true
    volumes:
      - /mnt/drone-dind:/var/lib/docker
