image: docker:git
services:
- docker:dind

stages:
- build

variables:
  CONTAINER_TEST_IMAGE: gitlab.omilia.com:1986/nlu-studio/compose:$CI_COMMIT_SHA

before_script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab.omilia.com:1986

build:
  tags:
    - docker-dind
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
